---
- name: Prepare
  hosts: all

  tasks:
    - name: Override default variables with facts
      ansible.builtin.set_fact:
        sandbox_domain: learningsandbox.test
        sandbox_domain_aliases: []
        sandbox_environment: development
        sandbox_versions:
          - tag: v4.3.2 
            version: '4.3'

- name: Import main playbook
  ansible.builtin.import_playbook: ../../main.playbook.yml
