---
# This file is part of Learning Sandbox Online.
#
# Learning Sandbox Online is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Learning Sandbox Online is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Learning Sandbox Online. If not, see <https://www.gnu.org/licenses/>.

##
# Tasks for clearning up the objects left over for resetting a Moodle instance.
#
# @copyright  2023 Geoffrey Bernardo van Wyk (https://geoffreyvanwyk.dev)
##

- name: Drop fresh database {{ item }}
  become: yes
  become_user: postgres
  community.postgresql.postgresql_db:
    name: moodle-{{ item | replace('.', '') }}-fresh
    state: absent

- name: Drop next database {{ item }}
  become: yes
  become_user: postgres
  community.postgresql.postgresql_db:
    name: moodle-{{ item | replace('.', '') }}-next
    state: absent

- name: Delete fresh moodledata archive {{ item }}
  become: yes
  ansible.builtin.file:
    path: "{{
      '/var/www/moodledata-'
      + sandbox_domain
      + '-moodle-'
      + item
      + '-fresh.tar.gz' }}"
    state: absent

- name: Delete fresh moodledata {{ item }}
  become: yes
  ansible.builtin.file:
    path: /var/www/moodledata-{{ sandbox_domain }}-moodle-{{ item }}-fresh
    state: absent

- name: Delete current moodledata {{ item }}
  become: yes
  ansible.builtin.file:
    path: /var/www/moodledata-{{ sandbox_domain }}-moodle-{{ item }}-current
    state: absent
