---
# This file is part of Learning Sandbox Online.
#
# Learning Sandbox Online is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Learning Sandbox Online is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Learning Sandbox Online. If not, see <https://www.gnu.org/licenses/>.

##
# Tasks for preparing the reset of a particular version of Moodle.
#
# @copyright  2023 Geoffrey Bernardo van Wyk (https://geoffreyvanwyk.dev)
##

- name: Initialize moodledata for reset [{{ sandbox_item.version }}]
  when: not sandbox_stat_moodledata_archive.stat.exists
  become: yes
  block:
    - name: Rename moodledata as fresh [{{ sandbox_item.version }}]
      ansible.builtin.command:
        cmd: mv {{ sandbox_moodledata }} {{ sandbox_moodledata_fresh }}
        creates: "{{ sandbox_moodledata_fresh }}"

    - name: Archive fresh moodledata [{{ sandbox_item.version }}]
      community.general.archive:
        path: "{{ sandbox_moodledata_fresh }}"
        dest: "{{ sandbox_moodledata_archive }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: u=rw,g=r,o=r

    - name: Rename fresh moodledata to current [{{ sandbox_item.version }}]
      ansible.builtin.command:
        cmd: mv {{ sandbox_moodledata_fresh }} {{ sandbox_moodledata_current }}
        creates: "{{ sandbox_moodledata_current }}"

    - name: Turn moodledata into link [{{ sandbox_item.version }}]
      ansible.builtin.file:
        src: "{{ sandbox_moodledata_current }}"
        dest: "{{ sandbox_moodledata }}"
        state: link

    - name: Extract fresh moodledata [{{ sandbox_item.version }}]
      ansible.builtin.unarchive:
        remote_src: yes
        src: "{{ sandbox_moodledata_archive }}"
        dest: /var/www

    - name: Set permissions for fresh moodledata [{{ sandbox_item.version }}]
      ansible.builtin.file:
        path: "{{ sandbox_moodledata_fresh }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: www-data
        mode: u=rwX,g=rwX,o=rwX

- name: Initialize database for reset [{{ sandbox_item.version }}]
  when: not sandbox_stat_moodledata_archive.stat.exists
  become: yes
  become_user: postgres
  block:
    - name: Copy fresh database [{{ sandbox_item.version }}]
      community.postgresql.postgresql_db:
        name: "{{ sandbox_database_fresh }}"
        state: present
        template: "{{ sandbox_database }}"

    - name: Copy next database [{{ sandbox_item.version }}]
      community.postgresql.postgresql_db:
        name: "{{ sandbox_database_next }}"
        state: present
        template: "{{ sandbox_database_fresh }}"
