---
# This file is part of Learning Sandbox Online.
#
# Learning Sandbox Online is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Learning Sandbox Online is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Learning Sandbox Online. If not, see <https://www.gnu.org/licenses/>.

##
# Wrapper tasks for preparing or performing the reset of a particular version of
# Moodle.
#
# @copyright  2023 Geoffrey Bernardo van Wyk (https://geoffreyvanwyk.dev)
##

- name: Set independent variables [{{ sandbox_item.version }}]
  ansible.builtin.set_fact:
    sandbox_database: >-
      moodle-{{ sandbox_item.version | replace('.', '') }}
    sandbox_moodle_html: /var/www/html/moodle-{{ sandbox_item.version }}
    sandbox_moodledata: >-
      /var/www/moodledata-{{ sandbox_domain }}-moodle-{{ sandbox_item.version }}
    sandbox_php_version: "{{
           '8.1' if (sandbox_item.branch == 'MOODLE_402_STABLE') or
                    (sandbox_item.branch == 'MOODLE_401_STABLE')
      else '8.0' if (sandbox_item.branch == 'MOODLE_400_STABLE') or
                    (sandbox_item.branch == 'MOODLE_311_STABLE')
      else '7.4' }}"

- name: Set dependent variables [{{ sandbox_item.version }}]
  ansible.builtin.set_fact:
    sandbox_database_fresh: "{{ sandbox_database }}-fresh"
    sandbox_database_next: "{{ sandbox_database }}-next"
    sandbox_database_old: "{{ sandbox_database }}-old"
    sandbox_moodledata_fresh: "{{ sandbox_moodledata }}-fresh"
    sandbox_moodledata_archive: "{{ sandbox_moodledata }}-fresh.tar.gz"
    sandbox_moodledata_current: "{{ sandbox_moodledata }}-current"
    sandbox_moodledata_old: "{{ sandbox_moodledata }}-old"

# Additional database connections will prevent the copying of the database.
- name: Ensure no extra database connections [{{ sandbox_item.version }}]
  block:
    # Moodle maintenance mode is enabled to stop the scheduled tasks which might
    # make connections to the database.
    # yamllint disable-line rule:line-length
    # @see {@link https://docs.moodle.org/403/en/Maintenance_mode#CLI_maintenance_mode}
    - name: Enable Moodle's maintenance mode [{{ sandbox_item.version }}]
      ansible.builtin.command:
        chdir: "{{ sandbox_moodle_html }}"
        cmd: php{{ sandbox_php_version }} admin/cli/maintenance.php --enable
      # `changed_when` is actually always `yes` in this case, but it is set to
      # `no` to pass Molecule's idempotency test. The other option of adding a
      # tag `molecule-idempotency-notest` would not work, because with that tag
      # Molecule would skip this task which will make the playbook fail for the
      # very reason the task is here in the first place.
      changed_when: no

    - name: Restart database to kill connections [{{ sandbox_item.version }}]
      become: yes
      ansible.builtin.sysvinit:
        name: postgresql
        state: restarted
      # `changed_when` is actually always `yes` in this case, but it is set to
      # `no` to pass Molecule's idempotency test. The other option of adding a
      # tag `molecule-idempotency-notest` would not work, because with that tag
      # Molecule would skip this task which will make the playbook fail for the
      # very reason the task is here in the first place.
      changed_when: no

- name: Does archive of moodledata exists [{{ sandbox_item.version }}]?
  ansible.builtin.stat:
    path: "{{ sandbox_moodledata_archive }}"
  register: sandbox_stat_moodledata_archive

- name: Prepare or perform reset [{{ sandbox_item.version }}]
  ansible.builtin.include_tasks: "{{ sandbox_reset_step }}_moodle_reset.yml"

- name: Disable Moodle's maintenance mode {{ sandbox_item.version }}
  ansible.builtin.command:
    chdir: "{{ sandbox_moodle_html }}"
    cmd: php{{ sandbox_php_version }} admin/cli/maintenance.php --disable
  # `changed_when` is actually always `yes` in this case, but it is set to
  # `no` to pass Molecule's idempotency test. The other option of adding a
  # tag `molecule-idempotency-notest` would not work, because with that tag
  # Molecule would skip this task which would leave the Moodle instance in
  # maintenance mode, which is not what we might want with future tests.
  changed_when: no
