---
# This file is part of Online Learning Sandbox.
#
# Online Learning Sandbox is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Online Learning Sandbox is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# Online Learning Sandbox. If not, see <https://www.gnu.org/licenses/>.

##
# Primary playbook of this project.
#
# @copyright  2023 Geoffrey Bernardo van Wyk (https://geoffreyvanwyk.dev)
##

- name: Set up Homepage
  ansible.builtin.import_playbook: ./homepage.yml

- name: Install Moodle instances
  ansible.builtin.import_playbook: ./moodle.yml
